@startuml

[电商平台] -up-> [前台]
[电商平台] -down-> [后台]

[前台] -up-> [商品列表]
[前台] -up-> [商品详情]
[前台] -up-> [购物车]
[前台] -up-> [下单支付]
[前台] -up-> [个人中心]
[前台] -up-> [登录注册]
[前台] -up-> [网站首页]


[后台] -down-> [商品管理]
[后台] -down-> [订单管理]
[后台] -down-> [权限管理]
[后台] -down-> [地区管理]

@enduml